spring:
  application:
    name: danbi
  # Properties 파일 - Thymeleaf 설정
  thymeleaf:
    enabled:true
    cache:false
    check-template-location:true
    prefix:classpath:/templates/
    suffix:.html
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://27.35.76.169:3306/wind?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tiger
    initialization-mode: always
    dbcp2.validation-query: SELECT
#logging
#logging.logback.rollingpolicy.max-history: 로그 파일을 유지할 기간(일수)을 설정한다. 여기서는 30일 간의 로그만 유지하도록 했다.
#logging.logback.rollingpolicy.max-file-size: 로그 파일 1개의 최대 용량(size)를 설정한다. 여기서는 100MB로 설정했다.
#logging.file.name: 로그 파일의 이름을 설정한다. 여기서 logs/sbb.log는 logs 디렉터리의 하위에 sbb.log라는 이름으로 로그 파일을 생성하라는 의미이다.
#logging.logback.rollingpolicy.file-name-pattern: 로그 파일의 용량이 설정한 용량을 초과하거나 날짜가 변경될 경우 새로이 만들어질 로그 파일의 이름에 관한 규칙(pattern)을 설정한다.
#logging.pattern.dateformat: 로그 출력 시 출력하는 날짜와 시간의 형식과 타임존(time zone)을 설정한다. 여기서는 Asia/Seoul로 설정했다. 만약 타임존을 설정하지 않을 경우 UTC 시간을 기준으로 출력한다.
logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.BasicBinder: TRACE
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/danbi.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul